"https://{default}/":
  type: upstream
  upstream: "varnish:http"
  cache:
      enabled: false
  redirects:
    paths:
      '/check-api':
        to: 'https://fivetran.com/check-api'
        code: 307
